<a href="https://colab.research.google.com/github/MorganDiaz2513892022/datawarehouse-seguros/blob/main/Copia_de_clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/MorganDiaz2513892022/datawarehouse-seguros.git

In [16]:
import pandas as pd

In [25]:
#ruta almacenada en github
url = "https://raw.githubusercontent.com/MorganDiaz2513892022/datawarehouse-seguros/refs/heads/main/data/clientes.csv"

In [24]:
#Lectura del archivo
df = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [43]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,HOMBRE,2011-11-24,Sanmiguel,NAN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,NaT,Sta. Ana,NAN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,MASCULINO,NaT,S. Miguel,NAN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,MASCULINO,NaT,Lalibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945-08-02,San Salvador,PYME

BLOQUE 2: Exploración del DATASET

In [41]:
print("Primeras filas del dataset")
display(df.head())

Primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,HOMBRE,2011-11-24,Sanmiguel,NAN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,NaT,Sta. Ana,NAN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,MASCULINO,NaT,S. Miguel,NAN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,MASCULINO,NaT,Lalibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945-08-02,San Salvador,PYME

In [27]:
print("Dimensiones del dataset (Filas, Columnas)")
print(df.shape)

Dimensiones del dataset (Filas, Columnas)
(3030, 7)

In [28]:
print("columnas del dataset")
print(df.columns)

columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [29]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [30]:
print("valores nulos por columna")
print(df.isnull().sum())

valores nulos por columna
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [31]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

BLOQUE 3: Limpieza de datos

In [32]:
#Elimina espacio vacion al inicio y al final en columnas de texto
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

In [33]:
#normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [34]:
#normalizar el email
df["email"]=df["email"].str.lower()

In [35]:
#Normalizar genero
df["genero"]=df["genero"].str.upper()

In [38]:
#Convertir fecha de nacimiento a formato fecha
df['fecha_nacimiento']=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

In [44]:
#Normalizar ciudad
df["ciudad"]=df['ciudad'].str.title()
df['ciudad']=df['ciudad'].astype(str)
df['ciudad']=df['ciudad'].str.strip()
df['ciudad']=df['ciudad'].str.upper()

In [40]:
#Limpieza de segmento
df['segmento']=df['segmento'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

BLOQUE 4: VALIDACION

In [ ]:
#crear columna para registrar errores